### ISSUE TITLE
fail to command: nimble install easywave

### ISSUE THREAD

**Issue by nnahito** [johnnovak/easywave#1]
I want to use easywave.
So I executed `nimble install easywave` command.

However, the following error occurred.

```
Downloading Official package list
    Success Package list downloaded.
       Tip: 3 messages have been suppressed, use --verbose to show them.
     Error: Package not found.
```

Is it possible to modify this?

My environment is:

- Windows 10
- MacOS X Mojave
- nim 0.20.2

Thank you.

**Comment by johnnovak** [comment]
Check the top of the readme 😄
