### ISSUE TITLE
Nimble can't find easywave :(

### ISSUE THREAD

**Issue by HughPH** [johnnovak/easywave#2]
```
$ nimble install easywave
    Prompt: easywave not found in any local packages.json, check internet for updated packages? [y/N]
    Answer: y
Downloading Official package list
    Success Package list downloaded.
       Tip: 3 messages have been suppressed, use --verbose to show them.
     Error: Package not found.
```

**Comment by johnnovak** [comment]
Check the README:

> Work in progress, not ready for public use yet!

**Comment by HughPH** [comment]
nim-mod has a dependency on easywave, so this caveat should probably be included in the nim-mod readme.

**Comment by johnnovak** [comment]
> nim-mod has a dependency on easywave, so this caveat should probably be included in the nim-mod readme.

Ah, good point.
