### ISSUE TITLE
enterGroup(rr) errors

### ISSUE THREAD

**Issue by ingoogni** [johnnovak/easywave#3]
.nimble\pkgs\easywave-0.1.0\easywave.nim(265, 7) Error: expression 'enterGroup(rr)' is of type 'ChunkInfo' and has to be used (or discarded)

commenting out the line seems to work (so far)

Nim Compiler Version 1.4.8 [Windows: amd64]

**Comment by johnnovak** [comment]
Pushed fix (and you should not comment that line out).
